### ISSUE TITLE
feat: `FIREBIRD_ALIASES` variable

### ISSUE THREAD

**Issue by DeadNews** [fdcastel/firebird-docker#10]
`jacobalberty/firebird-docker` supports `FIREBIRD_ALIASES` environment variable:

```yml
FIREBIRD_ALIASES: ${DB_NAME}=/firebird/data/${DB_NAME}.fdb;
```

It would be nice if there was support for this as well.

Related issue: https://github.com/jacobalberty/firebird-docker/issues/47, https://github.com/jacobalberty/firebird-docker/commit/8c1a3df5e977b58d1255733b6776910bffb0330e
Related code: [docker-entrypoint.sh](https://github.com/jacobalberty/firebird-docker/blob/bc5ffbf0d57a9d223a6833f10452e34266e729d9/docker-entrypoint.sh#L201-L207), [registerDatabase.sh](https://github.com/FirebirdSQL/firebird/blob/9694399ea646d0678d61db0727a6271e792cacca/builds/install/posix-common/registerDatabase.sh.in#L117)

ref: https://github.com/fdcastel/firebird-docker/issues/8

**Comment by fdcastel** [comment]
Let's continue this on #8.
