### ISSUE TITLE
allow the sysdba password to be set permanently without setting the environment variable `FIREBIRD_ROOT_PASSWORD` and without generating `/opt/firebird/SYSDBA.password`

### ISSUE THREAD

**Issue by level420** [fdcastel/firebird-docker#5]
The current behavior is, that if I'm setting the environment variable `FIREBIRD_ROOT_PASSWORD` the password therein is used correctly, but also written to the file `/opt/firebird/SYSDBA.password`, so that the unhashed password is accessible within the container, and will have to be in some file outside the container (e.g. .env or docker-compose.yml etc.).

If I'm not setting `FIREBIRD_ROOT_PASSWORD`, a new password is generated and set for sysdba, every time I'm starting the container, and it is also written to `/opt/firebird/SYSDBA.password`.

My use case is to store securtiy5.fdb in a permanent volume after first startup, having set the SYSDBA password before and having configured users, and then leave it alone, with no further change by entrypoint.sh and no further need to set `FIREBIRD_ROOT_PASSWORD`, and without having the password documented in `/opt/firebird/SYSDBA.password`.

Maybe this could be achieved by some environment variable like `FIREBIRD_PERMANENT_SECURITY_DB` or similar, which, when set to true, ignores all settings related to passwords and usernames.

That would be great!

**Comment by fdcastel** [comment]
Something like this?

```bash
cd /tmp

DOCKER_IMAGE=ghcr.io/fdcastel/firebird:5

# Start ephemeral container and extract the (empty) security database.
CID=$(docker run --detach $DOCKER_IMAGE)
docker stop $CID
docker cp $CID:/opt/firebird/security5.fdb .
docker rm $CID

# Setup security.
docker run \
    -v ./security5.fdb:/opt/firebird/security5.fdb \
    $DOCKER_IMAGE \
    /opt/firebird/bin/isql -b security.db <<-EOL
        CREATE OR ALTER USER alice
            PASSWORD 's3cret'
            GRANT ADMIN ROLE;
        
        CREATE OR ALTER USER hatter
            PASSWORD 'm@d';
EOL

# Start service with the alternative security database
docker run \
    --detach \
    -v ./data:/run/firebird/data \
    -v ./security5.fdb:/opt/firebird/security5.fdb \
    $DOCKER_IMAGE
```

**Comment by level420** [comment]
@fdcastel thank you for the code, but I meant the `SYSDBA` password. How can I persist my own password, without defining the environment variable `FIREBIRD_ROOT_PASSWORD`? Currently the only possibility is to set it into `FIREBIRD_ROOT_PASSWORD` which means I have to write it as plain text into a script, .env file, systemd service unit, docker-compose.yml file, whatever. And it don't want to have it to be written into `/opt/firebird/SYSDBA.password`.

Reading the docs (https://github.com/fdcastel/firebird-docker/blob/master/README.md?plain=1#L129-L134) I got the impression that if `FIREBIRD_ROOT_PASSWORD` is not set, a password is generated on every container restart. But I think the documentation is wrong, as the password is generated only on image build. So I was wrong in my initial post that the password is generated on every container restart. I'ts always the same default `SYSDBA` password.

For now I'm mapping an empty `/opt/firebird/SYSDBA.password` into the container, which avoids resetting the `SYSDBA` password on every container startup. But that feels just like a workaround, not a solution.

Mapping the security database into the container is not the problem that's what I'm doing anyway.

**Comment by fdcastel** [comment]
@level420 I'm planning to change the `FIREBIRD_ROOT_PASSWORD` behavior to the following:

- If `FIREBIRD_ROOT_PASSWORD` is set, `SYSDBA` password will be changed. And the file `/opt/firebird/SYSDBA.password` will be removed.
- Otherwise, nothing is done. The original behavior of Firebird installer is kept (random password generated and acessible from `/opt/firebird/SYSDBA.password`).

What do you think?

I too don't like the idea of `/opt/firebird/SYSDBA.password` keeping the password.

**Comment by fdcastel** [comment]
@level420 I pushed these changes in https://github.com/fdcastel/firebird-docker/commit/3c92342529400e131f6c63038b5fc3e75014c402.

I believe this should fix all your worries about the storage of the SYSDBA password. I'm closing this issue now, but feel free to comment or reopen it if needed."
